### ISSUE TITLE
MongoDB 16MB Limit Exceeded by 12MB File?

### ISSUE THREAD

**Issue by eoinmiller-sfdc** [spender-sandbox/cuckoo-modified#100]
Keep seeing this pop up in my logs:

<pre>2016-04-22 11:36:07,541 [lib.cuckoo.core.plugins] DEBUG: Executing reporting module "MongoDB"
2016-04-22 11:36:10,412 [modules.reporting.mongodb] WARNING: results['behavior']['enhanced'] deleted due to >16MB size (12MB)
2016-04-22 11:36:14,381 [root] INFO: Task #264: reports generation completed</pre>

In checking, the BSON doc is 16mb:
<pre>cuckoo@spender:~/cuckoo-modified/storage/analyses/264/logs$ ls -laFh *.bson
-rw-r--r-- 1 cuckoo cuckoo 1.7M Apr 22 11:34 1460.bson
-rw-r--r-- 1 cuckoo cuckoo 2.9K Apr 22 11:34 2468.bson
-rw-r--r-- 1 cuckoo cuckoo 237K Apr 22 11:34 2520.bson
-rw-r--r-- 1 cuckoo cuckoo  37K Apr 22 11:34 2548.bson
-rw-r--r-- 1 cuckoo cuckoo 269K Apr 22 11:34 2644.bson
-rw-r--r-- 1 cuckoo cuckoo 2.5K Apr 22 11:34 2748.bson
-rw-r--r-- 1 cuckoo cuckoo 3.8M Apr 22 11:34 2788.bson
-rw-r--r-- 1 cuckoo cuckoo 3.2M Apr 22 11:34 2884.bson
-rw-r--r-- 1 cuckoo cuckoo 2.9K Apr 22 11:34 2940.bson
-rw-r--r-- 1 cuckoo cuckoo  16M Apr 22 11:34 3052.bson <<<----- 
-rw-r--r-- 1 cuckoo cuckoo 377K Apr 22 11:34 528.bson
-rw-r--r-- 1 cuckoo cuckoo  46K Apr 22 11:34 664.bson
-rw-r--r-- 1 cuckoo cuckoo  40K Apr 22 11:34 812.bson
-rw-r--r-- 1 cuckoo cuckoo 358K Apr 22 11:34 904.bson</pre>

**Comment by KillerInstinct** [comment]
Yep, this is currently unavoidable for 'large' files. The debug code in there that removes the problem keys isn't exact as we only cound data in key/value pairs and don't account for the structures themselves. EG list/dicts and other things. These structures take up space to store, which that code unfortunately does not account for when calculating the size.

**Comment by kevthehermit** [comment]
Why not implement GridFS i do this in projects that need mongo to store large files, And its in Cuckoo Main branch already

**Comment by spender-sandbox** [comment]
Because the problem has nothing to do with the storing of the file itself.

-Brad

**Comment by KillerInstinct** [comment]
@kevthehermit To explain a little:

GridFS is meant to be used for file storage. In our case the issue is a specific dictionary is larger than the maximum document size (as Brad was saying, the .bson files aren't the actual cause, it's the parsed .bson into .json for the results dict that's the issue)

So if we were to store the .json in GridFS, there would still be no way to search the data in a way that doesn't produce long wait times (for HTTP responses at the end of the day) so from the web interface perspective there is no difference from deleting the problematic key then storing it in GridFS. Honestly GridFS is just duplicating data stored on disk, which is most of the reason it was removed from this fork and also why upstream has an open issue ticket to remove GridFS.

The only reason I would see a potential use of GridFS would be to store away the .bson files so that at a later date if we wanted to reprocess an analysis, we could pull those .bson files back out to reprocess the analysis. But at the same time, I don't see why this couldn't be done from disk either.
