### ISSUE TITLE
Analyzing RTF documents

### ISSUE THREAD

**Issue by dforce** [spender-sandbox/cuckoo-modified#14]
Is there some kind of script to analyze RTF documents ?
When I run one I get an error stating :
" is not a supported file type, cannot extract VBA Macros "

Thanks
Miguël

**Comment by KillerInstinct** [comment]
RTF files can't have VBA macros that I'm aware of. Got a sample / are you sure it's not libmagic classifying it incorrectly?

**Comment by dforce** [comment]
It is not libmagic classifying it incorrectly, when I look at it in hexeditor it starts with the rtf header.
I have a sample and can be found https://app.box.com/s/7uita3p8n0bdszck8m9jhqapxa21wzs5

Miguël

**Comment by KillerInstinct** [comment]
I'm going to assume this is an exploit. When I run this word basically does nothing for me. Also the [VT](https://www.virustotal.com/en/file/6a0bcd195d8ae990daadac89d610363446bb06fb8f15f1ae2721ef1367935f14/analysis/) analysis is littered with exploit signatures. The reason you get the error of "cannot extract VBA macros" is simply because there is none. Since this file has a .doc extension, we try to pass it into oletools for parsing and at that point it gives you that error message (which is non-critical to cuckoo).

**Comment by dforce** [comment]
Isn't there a way to get the metadata from an rtf file, like at VT ?

**Comment by spender-sandbox** [comment]
There is, but it requires a private VT API key, it can't be done with a VT Intelligence key AFAIK.

-Brad
