### ISSUE TITLE
File not executing during analysis

### ISSUE THREAD

**Issue by dforce** [spender-sandbox/cuckoo-modified#19]
When I run a certain file, this is not execute for analysis, no screenshots shown

When I run within the cuckoosandbox-dev it is executed and I see the screenshots of the execution.

What could be the problem ?

Thanks
Miguël

**Comment by spender-sandbox** [comment]
I need more information, I can't really do anything at all with a report like this.

-Brad

**Comment by dforce** [comment]
File can be found here https://app.box.com/s/bieh9hiqwicdlgnbiv5iyd6fpryvlbxi
Usual password.

It is a ransomware file. When I run it, it is not executed within the VM, there is nothing changing on the system. The state of the VM is the same as at the beginning of the analysis.

Running the same file within the cuckoosandbox-dev I see the the file is executed, things are changing on the system and I see the ransomware notice.

Using the same VM for both analyses.

**Comment by spender-sandbox** [comment]
Is there anything in the analysis.log?

**Comment by dforce** [comment]
Log file can be found here https://app.box.com/s/5z6xs7c24x2ouurga71axg0ewhyuc89w
Usual password

**Comment by spender-sandbox** [comment]
This is the same issue as here: https://github.com/spender-sandbox/cuckoo-modified/issues/70

I think it's a problem with your .NET installation -- it runs fine for me in Win 7 with injection.

-Brad

**Comment by dforce** [comment]
I want to come back on this one.
.Net installations are 3.5, 4.5 and 4.6.2 installed but still the file is not executed.

Any other suggestions ?

**Comment by spender-sandbox** [comment]
Your log shows it is executed.  If you want to see the ransomware notice you'll need to extend the timeout on the analysis and enable the "enforce timeout" option.  If upstream's version of cuckoo is displaying the notice as you expect, it can only be because it's running the sample slower than we do.  The important part about this sample is that the actual ransomware encryption is done in a process started via a created Task Scheduler COM object, which is doing the process creation from the associated svchost process.  Neither ours nor upstream's code will ever see the creation of that process since neither of us have the COM object hooking to handle it.

-Brad

**Comment by spender-sandbox** [comment]
Just wrote up some code that handles this case properly, gives us full visibility over the malware, and properly identifies it was ctb-locker from existing signatures.  I'll commit it either today or next week.

**Comment by dforce** [comment]
Ok, thanks
Keep you posted of the result.

**Comment by dforce** [comment]
Have you already commit the code that handles this case properly ?

**Comment by spender-sandbox** [comment]
Not yet, cleaning it up still.

-Brad

**Comment by spender-sandbox** [comment]
Resolved with the latest commit.

**Comment by dforce** [comment]
It didin't solved the problem for me, couldn't see any btc-locker screens (did not get full visibility over the malware, and didn't properly identified it was ctb-locker from existing signatures).
I am using Win7_64
Changed timeout to 600 and 1200 and also set force timeout.
Also changed the date of the virtual machine.
But no results.

**Comment by spender-sandbox** [comment]
There must be something else going on with your VM then -- it works fine here even on Windows 7 x64 (though there is an issue with a few of the 64-bit hooks due to differences in the 64-bit DLLs being used that I'll resolve soon, so we don't fire on as many signatures there as we should).  You'll have to give me more information, screenshots of the process tree, of the signature area, etc.

-Brad

**Comment by spender-sandbox** [comment]
Latest commits should have improved analysis some more -- it'll fire on more existing signatures.

**Comment by dforce** [comment]
Will check and run it.
Keep you posted on that.

**Comment by dforce** [comment]
Still not seeing any ransomware warning.
Asked files can be found here https://app.box.com/s/ceas8im5oiw285x1tjr8uhrbg7b26z6c

**Comment by dforce** [comment]
After updating the VM I get everything except I don't see the desktop changing. I also see some files being encrypted but not all.

Is there something else I can do to see all this, like desktop being changed and encrypting all files (pdf, doc, jpg etc ...) ?

**Comment by KillerInstinct** [comment]
Try a longer timeout?

**Comment by dforce** [comment]
Already tried that, set it to 600 and 1200 seconds, but made difference.
