### ISSUE TITLE
Merging Cuckoo-2.0 RC1 Changes

### ISSUE THREAD

**Issue by jbertman** [spender-sandbox/cuckoo-modified#21]
The Cuckoo team has released Cuckoo-2.0 RC1 today: https://cuckoosandbox.org/2016-01-21-cuckoo-sandbox-20-rc1.html

There are a lot of great features added. TL;DR:
* Monitoring 64-bit Windows applications and samples.
* Mac OS X, Linux, and Android analysis support.
* Integration with Suricata, Snort, and Moloch.
* Interception and decryption of TLS/HTTPS traffic.
* Per analysis network routing including VPN support.
* Over 300 signatures for isolating and identifying malicious behavior.
* Volatility baseline capture to highlight the changes during the analysis.
* Extraction of URLs from process memory dumps.
* Possibility to run extra services in separate VMs next to the analysis.
* Maliciousness scoring - does this analysis show malicious behavior?
Many bug fixes, improvements, tweaks and automation improvements.

Many of these features are already implemented in this fork, but we are missing cross-platform analysis, TLS/HTTPS decryption, network routing (partial), new signatures, Volatility baselines, URL extraction, and same-network services. Maybe we would benefit from listing changes that wouldn't conflict with this fork?

**Comment by KillerInstinct** [comment]
I can comment on the "new signatures" part of your issue as well as the volatility baselining.

I personally did a review of over 90% of the signatures that Redsocks.nl and in my experience nearly every single signature was based off of hard indicators like file names, mutexes, and registry keys. While the signatures were not "wrong" they failed to cover many cases where malware uses PRNG to generate file names, mutexes, reg keys, etc...

A good example would be their Upatre signatures, compared to our Upatre signature. We focus on actual behaviors of the malware instead of bland indicators. In some cases, we use broad indicators and couple it with unique behaviors (in the case of Nanocore for example) to achieve a much less false negative rate than what I reviewed from Redsocks.nl's signatures.

Ultimately on top of that, it looked as if these signatures were generated on very small sample sizes of malware, perhaps 1-4 samples was enough to make some of their mutex signatures. I didn't want to suggest merging all of those signatures, when many of them would eat up processing cycles while having a higher false negative rate.

I have been in contact with @jbremer for basically any signature I develop that I think would be compatible+valuable with upstream. As I do not personally maintain an upstream cuckoo rig anymore, I just notify him of our code to eventually be merged when I commit it.

For the volatility code -- I've had that uncommited for a long time in my repo, however I never got it -properly- implemented. Much of the code was done by one of the users in IRC. (l0ngest I believe) I will hopefully have some time to get that incorporated soon, but I don't have a good timeline and have been pretty busy this past month.

**Comment by seanthegeek** [comment]
I don't mean to open a political can of worms by asking this...Many of these "new" features are (poorer) implementations of features that have been in this fork for over a year, so why did they spend so much time reinventing wheels instead of merging existing code from here? Just seems like completely unnecessary duplicated effort.

**Comment by botherder** [comment]
Firstly, the most significant additions are not even available in this fork, so what you're insinuating is just incorrect. I don't see any additional analyzers for other platforms here, and the entire Windows monitoring engine has been refactored basically from scratch. We don't merge this fork because no pull requests have ever come from this fork, pretty much because spender deliberately decided not to do so. It's his prerogative, as so is your prerogative to submit your contributions to upstream or to forks instead.
I'm not gonna dwell into the politics cause it is a heated discussion that we already had many times, but Cuckoo Sandbox is copyrighted to a no-profit foundation. We just can't merge code copyrighted by others without their consent.
If you want to see features upstream, contribute upstream, otherwise I'm really not sure what is that you're complaining about.

**Comment by seanthegeek** [comment]
I am well aware that the technical restructuring of this fork makes a merge extremely difficult. As someone who has used both projects, I like unique features from both. I'm not even sure which version to recommend. I just think it's a shame that the two are as separate as they are. The copyright issue makes perfect sense. My wording was poor. I apologise.

I'd love to port some of the features upstream, I'm not sure how to go about doing that without violating others copyright. I do have a few ideas for some new convenience features that I will gladly contribute to both projects in the near future.

**Comment by botherder** [comment]
The copyright issue is what we tried to resolve exactly with the Contributors License Agreement (as many other open source software projects did as well, in our space, Volatility is an example). If there are concerns with some wording with the CLA, we are open to discuss changes.

FWIW, I meant that the upstream Windows monitoring engine has been refactored from scratch.

**Comment by jbertman** [comment]
@KillerInstinct Thanks for the explanation. 

I was unaware of the ongoing copyright issue, as I've recently delved into this fork. I simply thought that we might benefit from a discussion about features we'd like to implement, referencing 2.0-RC1 as a possible template for the integration of specific modules. I would love to see some of bigger modules (other platforms, TLS/SSL, Volatility diffing), but it seems like we'll have problems outside of the merging. @botherder I don't mean to be uninformed, but could you elaborate a bit on how the CLA can help alleviate these problems? Are we trying to relicense the contributions that have been submitted?

**Comment by botherder** [comment]
The Foundation and the CLA were originally introduced to remove my exclusive ownership of the project and assign it to a no-profit with the intent to guarantee continuity to the project in the case (as it has happened) that I don't have the means to bring it forward alone. By doing so, the Foundation retains copyright on the contributed code under GPL license and the contributor retains a BSD-like licensed copy of it. If the community believes this is not the appropriate course of action I'm fine with re-evaluating options, but at the time it seemed logical to follow the example of larger projects and use standard documentation available online.
IIRC the disagreement with spender came with wording in the CLA mentioning that the Foundation is allowed to redistribute the code under any license, including commercial (as long as it is also licensed as GPL) kind of like nmap (https://nmap.org/npsl/npsl-annotated.html). Personally, given that it is a no-profit holding the copyright, I never saw this as a problem, and in fact we believed it could have been a sustainable model to fund the project. At this point, to be honest, personally I really couldn't care less about the wording or what licensing option the Agreement offers, but I do believe in the value of having a legal no-profit entity control and protect a software that we spent years developing.

**Comment by kevross33** [comment]
Outside of licensing I would say there are many changes in both branches that are beneficial and I don't want to get political or anything as we are all on the same team anyway & quite simply cuckoo is awesome and provides the very best alternative to commercial options which for many are unaffordable yet we face the same threats. So I am very grateful for this project and think all the work you guys have done is incredible and has really helped to improve IT security.

There has obviously been a lot of great working into Cuckoo 2.0 such as android analysis, Linux & Mac Analysis and volatility memory diffing is particularly interesting; for instance this paper by Sophos abut modifications by them using memory diffing for rootkit & bootkit analysis is interesting https://www.virusbtn.com/virusbulletin/archive/2015/01/vb201501-unveiling-kernel.

However I do find the current signatures in cuckoobox in need of improvement and a side by side of different malware payloads, downloaders and exploits (ignoring also the cuckoosploit stuff) it is more useful for me to use cuckoo-modified as I need quick extraction of indicators to zero in on and I need to make it easy for others I work with to determine maliciousness of say a office document and indicators.

Certainly the signatures are worth integrating to better highlight malicious activities. I know you said no commits have come from this brach for inclusion but I noticed that powershell.exe was a signature I did and is in the new 300 signatures. While I certainly don't object to it being in there & this is definately not a criticism as I encourage it I don't know then how it ended up being included unless it was cherry picked but I think more should be cherry picked :-)  

Certainly there are many features in this fork that I think would be a benefit in the main project (signatures, interface changes, JS and DOM hooks if not present although maybe now the VBE for macro malware would be useful being hooked too in both - http://joe4security.blogspot.co.uk/2015/05/dynamically-analyze-offices-marcos-by.html, https://hiddencodes.wordpress.com/2015/05/18/instrument-microsoft-office-applications-to-defeat-macro-obfuscations/), malheur etc but I think certainly you will see there are many good changes in this branch that could be worth integrating (along with checkpoint's interesting cuckoosploit which has stack pivot detection so provides DEP bypass detection and ROP detection). On the exploit front I noticed before pwnypot but I never got the chance to use it but it certainly looked like it had some interesting features too.

**Comment by botherder** [comment]
I hear you, we definitely haven't spent enough time building decent signatures or fixing the existing ones. FWIW, this is the reason why we kept the modules in a separate community repository. We don't want it to necessarily abide to any licensing obligations and have everybody feel they can freely contribute to it.

**Comment by jbremer** [comment]
Bit late to the party, but thanks for the constructive response @kevross33. I agree that we're still missing a fair amount of interesting signatures, but as pointed out by @botherder we can't just take (most of) them straight away, and also as I mentioned earlier; integration, testing, and maintenance of them takes a bunch of time as well - something that as of this moment none of us are getting paid for doing.
As a community project we try to keep up-to-date as much as possible - along with adding novel features as discussed elsewhere in this thread - but for some of us time that can be spent on the project is limited or is applied for specific use-cases which are not Signatures per se.
As @botherder guessed correctly, I indeed cherry-picked your Signature and improved it further to my needs - in this example that seems to have mostly been decoding the base64 command payload. Nothing interesting or ground-breaking about that, but again, takes time to test etc etc.

**Comment by kevross33** [comment]
Hi,

Thanks for the response to this point. I understand same as you I don't have much time with life, family & work.

I think the problem is where to begin. I would guess it may be easiest to start with each of the signatures which both branches cover and see what APIs, indicators, whitelists etc are different to bring their functionality in line with each other and then working on different signatures. Although obviously some differences can't be done until the necessary features are added in (stack pivot, java static analysis, PDF static analysis, office/macro static analysis etc).

My concern is that I believe this is something that should be looked at before the branches move too far apart meaning that the benefits from each are lost on the other and there is a lot of features in both and also a lot of work has been put in by many people and specifically Brad working both with Optiv and independently. I am aware also some companies use cuckoo-modified so the changes are useful: (https://blog.malwarebytes.org/threat-analysis/2015/08/automatic-analysis-using-malheur-and-cuckoo/, https://labs.opendns.com/2015/12/15/new-cuckoo-for-you/)

With the signatures also providing a lot of behaviour detail that should not be left behind because currently in a side by side while both sandboxes generate a lot of great data if it is purely the signatures that are looked at to cover the behaviour (ideally with the idea being as much as possible a malicious action can be identified to a user) I find this fork provides a more thorough and precise coverage. That isn't mean in anyway as a negative comment but just where do we go to get that all this into main branch?
